export default {
    help: [
        "info",
        "site info",
        "about",
        "about me",
        "social",
        "display social",
        "contactMe",
        "print email",
        "color",
        "customize the terminal",
        "cls",
        "clear the terminal",
    ],
    about: "SUP3R HERE!",
    social: "github/discord/instagram",
    contactMe: "send email",
    color: new Map([
        ["0", "Black"],
        ["8", "Grey"],
        ["1", "Dark Blue"],
        ["9", "Blue"],
        ["2", "Green"],
        ["a", "Lime"],
        ["3", "Aqua"],
        ["b", "Light Blue"],
        ["4", "Bordeaux"],
        ["c", "Red"],
        ["5", "Purple"],
        ["d", "Magenta"],
        ["6", "Olive"],
        ["e", "Yellow"],
        ["7", "Light Gray"],
        ["f", "White"],
    ]),
    cls: "clear console",
};
